### PR TITLE
work in all languages and change how dialog sort menu options work

### LINKED ISSUE #10: Essential features not working in other languages than English
This script in the current form basically requires having the UI in English because it relies on the button text and assumes it being English.
For starters: In German there's no button labeled "Expand here" to expand images (it's labeled "hier erweitern") or navigating pages fails while searching for "Next" and "Prev" (instead of "Weiter" and "Zurück").

LemmyTools had the same problem: https://github.com/howdy-tsc/LemmyTools/issues/35
And solved it this way: https://github.com/howdy-tsc/LemmyTools/pull/40

### PR DESCRIPTION
**Pull request by InfinibyteF4**
https://github.com/vmavromatis/Lemmy-keyboard-navigation/issues/10

- works with languages other than english. i did this on pawb.social, if your instance has buttons in a different order it might select the wrong buttons.

- changed how the sort menu options work in the dialog. instead of only being able to sort in the front page, you can sort in comment sections, your inbox, profiles, etc. The dialog text changes with the sort options.

- fix another spelling mistake (oops)

### CODE REVIEW

**Comment by vmavromatis** [comment]
Wow thank you so much man. I made you maintainer too just now :) 

As for this PR looks good, I tested in lemmy.world and beehaw.org with multiple languages.

**Comment by Lucki** [comment]
I think this missed Prev/Next page: https://github.com/vmavromatis/Lemmy-keyboard-navigation/blob/0d72cbaaf8936612f681bc467bcbe55c28d75451/lemmy-keyboard-navigation.user.js#L741

Also saw some problems expanding video previews but I'll have to investigate this more.

**Comment by vmavromatis** [comment]
@InfinibyteF4 I have no PC to make a PR but I think this must be 

const buttonText = event.code === nextPageKey ? document.querySelectorAll(".paginator>button")[1].innerHTML : document.querySelectorAll(".paginator>button")[0].innerHTML;

**Comment by InfinibyteF4** [comment]
@vmavromatis I'm away from home for a few days and don't have a computer with me either D:

If your code doesn't work try replacing lines 740-743 with this:

```
if (pageButtons && (document.getElementsByClassName('paginator').length > 0)) {
  if (event.code === nextPageKey) {
    document.getElementsByClassName("???")[?].click(); //next
  } else {
    document.getElementsByClassName("???")[?].click(); //prev
  }
}
```
and replace '???' with the class of the page navigation buttons and '?' to point to the next or previous buttons. (I can't see what they are on mobile)

**Comment by aglidden** [comment]
@InfinibyteF4 @vmavromatis I'm home and have a computer! ;-P

**Comment by vmavromatis** [comment]
@aglidden I think u made a typo 1 & 1 must be 1 & 0 ;)

**Comment by aglidden** [comment]
@vmavromatis Whoops! Darned copy and paste. Should be good now.

**Pull request merged**
