### PR TITLE
Multiple js files for old & new lemmy

### LINKED ISSUE #9: Update to work with old.lemmy codebase
Lemmy.world has implemented https://old.lemmy.world 
Your keyboard navigation code is great. I appreciate it greatly. Any chance you can get it to work with the modified front end? The code base is here:

https://github.com/rystaf/mlmym

### PR DESCRIPTION
**Pull request by vmavromatis**
Closes #9 

- Use a main js file to @require both js files
- Bump to 2.3

### CODE REVIEW

**Review by InfinibyteF4 — COMMENTED** [review]
Tested it just now & it works great, I like the modularity as well :>

**Comment by vmavromatis** [comment]
m2 ^_^

btw, I just learnt that greasy fork doesn't allow [external scripts](https://greasyfork.org/en/help/external-scripts), will see how to tackle that later on. Merged for now :)

**Comment by aglidden** [comment]
Looks like it'll work if you md5 hash the two scripts and add #md5=(hash) to the end of @require as per https://www.tampermonkey.net/documentation.php#api:Subresource_Integrity

**Comment by vmavromatis** [comment]
Wow @aglidden you were right :) I just did it and it worked https://greasyfork.org/en/scripts/470498-lemmy-keyboard-navigation/code however it complained about no code so I added a log line lol

**Pull request merged**
