### PR TITLE
added login redirect, more link shortcuts, link identifying numbers, smooth scrolling, code clarity changes

### PR DESCRIPTION
**Pull request by aglidden**
edited some code for clarity, since I was having trouble understanding what was going on

redirect logged out users to the login screen when accessing inbox/profile/etc... from the dashboard

added link number identifiers to selected elements and added shortcut keys 6-0 so selected comments with up to 10 links will be labeled and keyboard navigable

made scrolling smooth

### CODE REVIEW

**Comment by vmavromatis** [comment]
Wow thank you so much this is awesome. 

Somehow the arrow navigation in Links has broken, can you check? Also I think the smooth scrolling should be disabled when navigating with arrows - I tried navigating comments and it's a bit wonky. I will hold the merge for now so you can take a look

Actually, I think you should be a collaborator, everything you are doing for the project is in the right direction, and also I don't have much time to dedicate lately. I will add you if you don't have any objections. Maybe we can clarify what is next, I think the opened Issues are on point for the most part.

**Comment by aglidden** [comment]
Hmmm, I'll take a look at the link navigation later today. I'm also working on a tildes.net keyboard navigation script and I've been cross pollinating a lot of the code so I might have borked something there. 

I accepted the invite, thank you! I'll take a look at starting on the issues in the next few days. The configuration menu sounds like a great idea, and the locale thing hopefully won't be too hard as long as the classes/ids stay the same. Do you think the old.lemmy thing might be better off as a fork? It looks like the dom is very different.

**Comment by aglidden** [comment]
> Somehow the arrow navigation in Links has broken, can you check? Also I think the smooth scrolling should be disabled when navigating with arrows - I tried navigating comments and it's a bit wonky. I will hold the merge for now so you can take a look

Okay, I think the initial selection was broken by an error in the link numbering code, could you check to see if it's working for you now? I also set smooth scroll default to off and added page offset and "top navigation" options.

**Comment by vmavromatis** [comment]
Awesome - works now! 

Re. old memmy (mlmym), I would prefer ideally to have it work within this script. We can try it out and if it cannot work then do the fork.

**Comment by vmavromatis** [comment]
fyi - just realized there's a bug in this new version. When in arrow mode and links view. Hit X to expand image, loses focus.

**Comment by aglidden** [comment]
https://github.com/vmavromatis/Lemmy-keyboard-navigation/commit/887624d5225987c80b158ef97cfcef9772cac623

**Pull request merged**
