### PR TITLE
merge InfinibyteF4 branch into main

### PR DESCRIPTION
**Pull request by aglidden**
merges the infinibyte changes into main, preserving the Vim toggle flag, adding enter key comment collapse, save, and community key

### CODE REVIEW

**Comment by vmavromatis** [comment]
I did some basic testing and this looks really good, well done. Kudos for finding the easter egg branch also :)

**Comment by vmavromatis** [comment]
I see you have default HJKL navigation instead of arrows. Shall we keep it like that? I think most ppl prefer HJKL anyway, I'm in the minority here.

**Comment by aglidden** [comment]
> I see you have default HJKL navigation instead of arrows. Shall we keep it like that? I think most ppl prefer HJKL anyway, I'm in the minority here.

Ah, whoops. That's what I keep as my default, it must have jumped into the commit while I was testing things. Feel free to change it back if you're so inclined. 

I only managed to find the easter egg branch because I was trying to figure out how to merge @InfinibyteF4's fork and accidentally found that one. I'm not good with git. 

I'll be sure to fix and/or report any bugs I made, I'm sure I missed something in there.

**Comment by vmavromatis** [comment]
HJKL as default is good for now. Let's see when Google accepts my 1.8->1.9 update for the extension now... I would like to add a UI toggle as part of the extension

**Pull request merged**
